import { writeFile } from "node:fs/promises";
import type { Command } from "commander";
import pc from "picocolors";
import * as toml from "smol-toml";
import { generateCollection } from "../core/openapi/generate.ts";
import { loadOpenApiSpec } from "../core/openapi/loader.ts";

interface GenerateOptions {
  from: string;
  out: string;
  security?: string;
}

export function registerGenerateCommand(program: Command): void {
  program
    .command("generate")
    .description("Auto-scaffold a starter collection from an OpenAPI spec")
    .requiredOption("--from <spec>", "path to an OpenAPI 3.x spec (yaml or json)")
    .requiredOption("--out <path>", "output path for the generated collection .toml")
    .option(
      "--security <schemeName>",
      "when an operation accepts multiple auth schemes, prefer this securitySchemes name"
    )
    .action(async (options: GenerateOptions) => {
      const spec = await loadOpenApiSpec(options.from);
      const { meta, requests, reviewNotes } = generateCollection(spec, {
        preferredSecurityScheme: options.security,
      });

      const body = toml.stringify({ meta, request: requests });
      const header =
        reviewNotes.length > 0
          ? `# Generated by \`shimwire generate\` — review before relying on this in CI:\n${reviewNotes
              .map((note) => `#   - ${note}`)
              .join("\n")}\n\n`
          : `# Generated by \`shimwire generate\`\n\n`;

      await writeFile(options.out, header + body);

      console.log(pc.green(`Wrote ${requests.length} request(s) to ${options.out}`));
      if (reviewNotes.length > 0) {
        console.log(
          pc.yellow(`${reviewNotes.length} item(s) flagged for manual review — see file header.`)
        );
      }
    });
}
