import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { Command } from "commander";
import pc from "picocolors";
import * as toml from "smol-toml";
import { loadConfig } from "../core/config/config.ts";
import { generateCollection } from "../core/openapi/generate.ts";
import { loadOpenApiSpec } from "../core/openapi/loader.ts";

interface GenerateOptions {
  from?: string;
  out?: string;
  security?: string;
  allowLocal?: boolean;
  insecure?: boolean;
}

export function registerGenerateCommand(program: Command): void {
  program
    .command("generate")
    .description(
      "Auto-scaffold a starter collection from an OpenAPI spec (flags override .shimwire/config.toml [generate] defaults)"
    )
    .option("-f, --from <spec>", "path to an OpenAPI 3.x spec (yaml or json, or a URL)")
    .option("-o, --out <path>", "output path for the generated collection .toml")
    .option(
      "-s, --security <schemeName>",
      "when an operation accepts multiple auth schemes, prefer this securitySchemes name"
    )
    .option(
      "-l, --allow-local",
      "allow fetching --from specs from localhost/private-network URLs (disables swagger-parser's SSRF guard)"
    )
    .option(
      "-k, --insecure",
      "skip TLS certificate verification while fetching --from (self-signed/local dev certs)"
    )
    .action(async (options: GenerateOptions) => {
      const config = (await loadConfig()).generate ?? {};

      const from = options.from ?? config.from;
      const out = options.out ?? config.out;
      if (!from) {
        throw new Error(
          'Missing "from": pass --from <spec> or set generate.from in .shimwire/config.toml'
        );
      }
      if (!out) {
        throw new Error(
          'Missing "out": pass --out <path> or set generate.out in .shimwire/config.toml'
        );
      }
      const security = options.security ?? config.security;
      const allowLocal = options.allowLocal ?? config.allow_local ?? false;
      const insecure = options.insecure ?? config.insecure ?? false;

      const spec = await loadOpenApiSpec(from, { allowLocal, insecure });
      const { meta, requests, reviewNotes } = generateCollection(spec, {
        preferredSecurityScheme: security,
      });

      const body = toml.stringify({ meta, request: requests });
      const header =
        reviewNotes.length > 0
          ? `# Generated by \`shimwire generate\` — review before relying on this in CI:\n${reviewNotes
              .map((note) => `#   - ${note}`)
              .join("\n")}\n\n`
          : `# Generated by \`shimwire generate\`\n\n`;

      await mkdir(dirname(out), { recursive: true });
      await writeFile(out, header + body);

      console.log(pc.green(`Wrote ${requests.length} request(s) to ${out}`));
      if (reviewNotes.length > 0) {
        console.log(
          pc.yellow(`${reviewNotes.length} item(s) flagged for manual review — see file header.`)
        );
      }
    });
}
