import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { Command } from "commander";
import * as toml from "smol-toml";
import { withErrorHandling } from "../core/cliError.ts";
import { loadConfig } from "../core/config/config.ts";
import { log } from "../core/logger.ts";
import { buildWorkflowRequests } from "../core/openapi/generate.ts";
import { loadOpenApiSpec } from "../core/openapi/loader.ts";

export interface WorkflowOptions {
  from?: string;
  name?: string;
  endpoints?: string[];
  security?: string;
  allowLocal?: boolean;
  insecure?: boolean;
}

export async function runWorkflow(options: WorkflowOptions): Promise<void> {
  // Reuses [generate].from — a project generally has one spec it works
  // from, no need for a separate [workflow] config section just for that.
  const config = (await loadConfig()).generate ?? {};

  const from = options.from ?? config.from;
  if (!from) {
    throw new Error(
      'Missing "from": pass --from <spec> or set generate.from in .shimwire/config.toml'
    );
  }
  if (!options.name) {
    throw new Error('Missing "name": pass --name <workflowName>');
  }
  if (!options.endpoints || options.endpoints.length === 0) {
    throw new Error(
      'Missing "endpoints": pass --endpoints <id1,id2,...>, or run `shimwire cli` to pick them interactively'
    );
  }
  const allowLocal = options.allowLocal ?? config.allow_local ?? false;
  const insecure = options.insecure ?? config.insecure ?? false;

  log.dim(
    `Loading OpenAPI spec from ${from}${allowLocal ? " (--allow-local)" : ""}${insecure ? " (--insecure)" : ""}...`
  );
  const spec = await loadOpenApiSpec(from, { allowLocal, insecure });

  const { requests, reviewNotes } = buildWorkflowRequests(spec, options.endpoints, {
    preferredSecurityScheme: options.security,
  });

  const foundIds = new Set(requests.map((r) => r.id));
  const missing = options.endpoints.filter((id) => !foundIds.has(id));
  if (requests.length === 0) {
    throw new Error(
      `None of the given endpoints matched an operation in ${from} — run \`shimwire cli\` to see the available ids.`
    );
  }
  if (missing.length > 0) {
    log.warn(`Skipped unknown endpoint id(s): ${missing.join(", ")}`);
  }

  const out = join(process.cwd(), ".shimwire", "workflows", `${options.name}.toml`);
  const body = toml.stringify({ request: requests });
  const header =
    reviewNotes.length > 0
      ? `# Generated by \`shimwire workflow\` — review before relying on this in CI:\n${reviewNotes
          .map((note) => `#   - ${note}`)
          .join("\n")}\n\n`
      : `# Generated by \`shimwire workflow\`\n\n`;

  log.dim(`Writing ${out}...`);
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, header + body);

  log.success(`Wrote ${requests.length} request(s) to ${out}`);
  log.dim(`  add include = ["${options.name}"] to a collection's [meta] to reuse it`);
  if (reviewNotes.length > 0) {
    log.warn(`${reviewNotes.length} item(s) flagged for manual review — see file header.`);
  }
}

export function registerWorkflowCommand(program: Command): void {
  program
    .command("workflow")
    .description(
      "Save a hand-picked set of endpoints as a reusable .shimwire/workflows/<name>.toml"
    )
    .option("-f, --from <spec>", "path to an OpenAPI 3.x spec (yaml or json, or a URL)")
    .option("-n, --name <workflowName>", "workflow file to write, under .shimwire/workflows/")
    .option(
      "-e, --endpoints <ids>",
      "comma-separated request ids to include (see `shimwire cli` to pick interactively)"
    )
    .option(
      "-s, --security <schemeName>",
      "when an operation accepts multiple auth schemes, prefer this securitySchemes name"
    )
    .option(
      "-l, --allow-local",
      "allow fetching --from specs from localhost/private-network URLs (disables swagger-parser's SSRF guard)"
    )
    .option(
      "-k, --insecure",
      "skip TLS certificate verification while fetching --from (self-signed/local dev certs)"
    )
    .action(
      withErrorHandling(async (opts: WorkflowOptions & { endpoints?: unknown }) => {
        const endpoints =
          typeof opts.endpoints === "string"
            ? opts.endpoints
                .split(",")
                .map((id) => id.trim())
                .filter(Boolean)
            : undefined;
        await runWorkflow({ ...opts, endpoints });
      })
    );
}
